//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPark.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NPark.Domain.Resource.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource already exists..
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number must be empty for non-subscriber tickets.
        /// </summary>
        public static string CardNumber_NonRequired {
            get {
                return ResourceManager.GetString("CardNumber_NonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number is required for subscriber tickets.
        /// </summary>
        public static string CardNumber_Require {
            get {
                return ResourceManager.GetString("CardNumber_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number is required..
        /// </summary>
        public static string CardNumber_Required {
            get {
                return ResourceManager.GetString("CardNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking system configuration not found.
        /// </summary>
        public static string Configuration_NotFound {
            get {
                return ResourceManager.GetString("Configuration_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing schema is not configured for enter price type.
        /// </summary>
        public static string ConfigurationPricingSchema_Missing {
            get {
                return ResourceManager.GetString("ConfigurationPricingSchema_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password..
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsRepeated cannot be true when DurationType is Days..
        /// </summary>
        public static string Conflict_IsRepeated {
            get {
                return ResourceManager.GetString("Conflict_IsRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists..
        /// </summary>
        public static string Email_Exist {
            get {
                return ResourceManager.GetString("Email_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed parking slots must be greater than 0.
        /// </summary>
        public static string Invalid_AllowedParkingSlots {
            get {
                return ResourceManager.GetString("Invalid_AllowedParkingSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid..
        /// </summary>
        public static string Invalid_Email {
            get {
                return ResourceManager.GetString("Invalid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndTime cannot be earlier than StartTime..
        /// </summary>
        public static string Invalid_EndTime {
            get {
                return ResourceManager.GetString("Invalid_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry gates count must be at least 1.
        /// </summary>
        public static string Invalid_EntryGatesCount {
            get {
                return ResourceManager.GetString("Invalid_EntryGatesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit gates count must be at least 1.
        /// </summary>
        public static string Invalid_ExitGatesCount {
            get {
                return ResourceManager.GetString("Invalid_ExitGatesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image must be a valid image file (jpg, png, jpeg)..
        /// </summary>
        public static string Invalid_Image {
            get {
                return ResourceManager.GetString("Invalid_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID must be a valid 14-digit Egyptian ID..
        /// </summary>
        public static string Invalid_NationalId {
            get {
                return ResourceManager.GetString("Invalid_NationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long, with at least one uppercase letter, one lowercase letter, and one number..
        /// </summary>
        public static string Invalid_Password {
            get {
                return ResourceManager.GetString("Invalid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be a valid Egyptian phone number..
        /// </summary>
        public static string Invalid_PhoneNumber {
            get {
                return ResourceManager.GetString("Invalid_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid price type.
        /// </summary>
        public static string Invalid_PriceType {
            get {
                return ResourceManager.GetString("Invalid_PriceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid print type..
        /// </summary>
        public static string Invalid_PrintType {
            get {
                return ResourceManager.GetString("Invalid_PrintType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalDays must be greater than zero when DurationType is Days..
        /// </summary>
        public static string Invalid_TotalDays {
            get {
                return ResourceManager.GetString("Invalid_TotalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHours must be greater than zero when DurationType is Hours..
        /// </summary>
        public static string Invalid_TotalHour {
            get {
                return ResourceManager.GetString("Invalid_TotalHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid vehicle/passenger data type.
        /// </summary>
        public static string Invalid_VehiclePassengerData {
            get {
                return ResourceManager.GetString("Invalid_VehiclePassengerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price cannot be less than zero..
        /// </summary>
        public static string InvalidPrice {
            get {
                return ResourceManager.GetString("InvalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to he field {0} is required..
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderPriority must be unique..
        /// </summary>
        public static string OrderPiority_Unique {
            get {
                return ResourceManager.GetString("OrderPiority_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderPriority is required when IsRepeated is true..
        /// </summary>
        public static string OrderPiorityIsRequired {
            get {
                return ResourceManager.GetString("OrderPiorityIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value out of range for: {0}..
        /// </summary>
        public static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password do not match..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is required..
        /// </summary>
        public static string Phone_Required {
            get {
                return ResourceManager.GetString("Phone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing scheme not found.
        /// </summary>
        public static string PricingSchema_NotFound {
            get {
                return ResourceManager.GetString("PricingSchema_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricingSchemaId is required when PriceType is set to &apos;Enter.
        /// </summary>
        public static string PricingSchemaId_RequiredWhenEnter {
            get {
                return ResourceManager.GetString("PricingSchemaId_RequiredWhenEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing Scheme ID is required..
        /// </summary>
        public static string PricingSchemeId {
            get {
                return ResourceManager.GetString("PricingSchemeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code is required.
        /// </summary>
        public static string QrCode_Require {
            get {
                return ResourceManager.GetString("QrCode_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code must be a valid Base64 string.
        /// </summary>
        public static string QrInvalid {
            get {
                return ResourceManager.GetString("QrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role does not exist..
        /// </summary>
        public static string Role_Exist {
            get {
                return ResourceManager.GetString("Role_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is required..
        /// </summary>
        public static string Role_Requred {
            get {
                return ResourceManager.GetString("Role_Requred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while calculating salary, please try again later.
        /// </summary>
        public static string SalaryCalculate_Unexpected {
            get {
                return ResourceManager.GetString("SalaryCalculate_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber card is not valid for the current date.
        /// </summary>
        public static string Subscriber_Card_InvalidDate {
            get {
                return ResourceManager.GetString("Subscriber_Card_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber card not found.
        /// </summary>
        public static string SubscriberCard_NotFound {
            get {
                return ResourceManager.GetString("SubscriberCard_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket not found for the provided QR code.
        /// </summary>
        public static string Ticket_NotFound {
            get {
                return ResourceManager.GetString("Ticket_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while adding ticket, please try again later.
        /// </summary>
        public static string TicketAdd_Unexpected {
            get {
                return ResourceManager.GetString("TicketAdd_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GateId or UserId not found.
        /// </summary>
        public static string TokenInfo_Missing {
            get {
                return ResourceManager.GetString("TokenInfo_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalDays is required when DurationType is Days..
        /// </summary>
        public static string TotalDay_Require {
            get {
                return ResourceManager.GetString("TotalDay_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHours is required when DurationType is Hours..
        /// </summary>
        public static string TotalHour_Require {
            get {
                return ResourceManager.GetString("TotalHour_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID must be unique.
        /// </summary>
        public static string Unique_NationalId {
            get {
                return ResourceManager.GetString("Unique_NationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be unique..
        /// </summary>
        public static string Unique_Phone {
            get {
                return ResourceManager.GetString("Unique_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists.
        /// </summary>
        public static string UserName_Exist {
            get {
                return ResourceManager.GetString("UserName_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required.
        /// </summary>
        public static string UserName_Required {
            get {
                return ResourceManager.GetString("UserName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle number is required..
        /// </summary>
        public static string VehicleNumber_Required {
            get {
                return ResourceManager.GetString("VehicleNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string WrongLogin {
            get {
                return ResourceManager.GetString("WrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
