//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Domain.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name English  required.
        /// </summary>
        public static string Account_NameEn_Unique {
            get {
                return ResourceManager.GetString("Account_NameEn_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one site is required..
        /// </summary>
        public static string Account_Sites_Empty {
            get {
                return ResourceManager.GetString("Account_Sites_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites list is required..
        /// </summary>
        public static string Account_Sites_Required {
            get {
                return ResourceManager.GetString("Account_Sites_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already in use.
        /// </summary>
        public static string Email_Exist {
            get {
                return ResourceManager.GetString("Email_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is invalid..
        /// </summary>
        public static string Login_Email_Invalid {
            get {
                return ResourceManager.GetString("Login_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string Login_Email_Required {
            get {
                return ResourceManager.GetString("Login_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not exceed 128 characters..
        /// </summary>
        public static string Login_Password_MaxLength {
            get {
                return ResourceManager.GetString("Login_Password_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters..
        /// </summary>
        public static string Login_Password_MinLength {
            get {
                return ResourceManager.GetString("Login_Password_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string Login_Password_Required {
            get {
                return ResourceManager.GetString("Login_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductId is required.
        /// </summary>
        public static string Product_ProductId_Required {
            get {
                return ResourceManager.GetString("Product_ProductId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support end date is required.
        /// </summary>
        public static string Product_SupportEndDate_Required {
            get {
                return ResourceManager.GetString("Product_SupportEndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site English name is required..
        /// </summary>
        public static string Site_NameEn_Required {
            get {
                return ResourceManager.GetString("Site_NameEn_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site English name must be unique.
        /// </summary>
        public static string Site_NameEn_Unique {
            get {
                return ResourceManager.GetString("Site_NameEn_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products list cannot be empty when provided.
        /// </summary>
        public static string Site_Products_Empty {
            get {
                return ResourceManager.GetString("Site_Products_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Password not valid TryAgain!.
        /// </summary>
        public static string WrongLoginCredintial {
            get {
                return ResourceManager.GetString("WrongLoginCredintial", resourceCulture);
            }
        }
    }
}
