//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Domain.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name English  required.
        /// </summary>
        public static string Account_NameEn_Unique {
            get {
                return ResourceManager.GetString("Account_NameEn_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one site is required..
        /// </summary>
        public static string Account_Sites_Empty {
            get {
                return ResourceManager.GetString("Account_Sites_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites list is required..
        /// </summary>
        public static string Account_Sites_Required {
            get {
                return ResourceManager.GetString("Account_Sites_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already in use.
        /// </summary>
        public static string Email_Exist {
            get {
                return ResourceManager.GetString("Email_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is invalid..
        /// </summary>
        public static string Login_Email_Invalid {
            get {
                return ResourceManager.GetString("Login_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string Login_Email_Required {
            get {
                return ResourceManager.GetString("Login_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not exceed 128 characters..
        /// </summary>
        public static string Login_Password_MaxLength {
            get {
                return ResourceManager.GetString("Login_Password_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters..
        /// </summary>
        public static string Login_Password_MinLength {
            get {
                return ResourceManager.GetString("Login_Password_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string Login_Password_Required {
            get {
                return ResourceManager.GetString("Login_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic description must not exceed 2000 characters..
        /// </summary>
        public static string Product_DescriptionAr_MaxLength {
            get {
                return ResourceManager.GetString("Product_DescriptionAr_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English description must not exceed 2000 characters..
        /// </summary>
        public static string Product_DescriptionEn_MaxLength {
            get {
                return ResourceManager.GetString("Product_DescriptionEn_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image must be an image file (jpg, jpeg, png, webp)..
        /// </summary>
        public static string Product_Image_InvalidType {
            get {
                return ResourceManager.GetString("Product_Image_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size must not exceed 2 MB..
        /// </summary>
        public static string Product_Image_MaxSize {
            get {
                return ResourceManager.GetString("Product_Image_MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name is required..
        /// </summary>
        public static string Product_NameEn_Required {
            get {
                return ResourceManager.GetString("Product_NameEn_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductId is required.
        /// </summary>
        public static string Product_ProductId_Required {
            get {
                return ResourceManager.GetString("Product_ProductId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support end date is required.
        /// </summary>
        public static string Product_SupportEndDate_Required {
            get {
                return ResourceManager.GetString("Product_SupportEndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site English name is required..
        /// </summary>
        public static string Site_NameEn_Required {
            get {
                return ResourceManager.GetString("Site_NameEn_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site English name must be unique.
        /// </summary>
        public static string Site_NameEn_Unique {
            get {
                return ResourceManager.GetString("Site_NameEn_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products list cannot be empty when provided.
        /// </summary>
        public static string Site_Products_Empty {
            get {
                return ResourceManager.GetString("Site_Products_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be empty..
        /// </summary>
        public static string Ticket_Description_Empty {
            get {
                return ResourceManager.GetString("Ticket_Description_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must not exceed 2000 characters..
        /// </summary>
        public static string Ticket_Description_MaxLength {
            get {
                return ResourceManager.GetString("Ticket_Description_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string Ticket_Description_Required {
            get {
                return ResourceManager.GetString("Ticket_Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket id is required..
        /// </summary>
        public static string Ticket_Id_Required {
            get {
                return ResourceManager.GetString("Ticket_Id_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Egyptian mobile number.
        /// </summary>
        public static string Ticket_Phone_Invalid {
            get {
                return ResourceManager.GetString("Ticket_Phone_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required..
        /// </summary>
        public static string Ticket_Phone_Required {
            get {
                return ResourceManager.GetString("Ticket_Phone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found..
        /// </summary>
        public static string Ticket_Product_NotFound {
            get {
                return ResourceManager.GetString("Ticket_Product_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductId is required..
        /// </summary>
        public static string Ticket_ProductId_Required {
            get {
                return ResourceManager.GetString("Ticket_ProductId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity is invalid..
        /// </summary>
        public static string Ticket_Severity_Invalid {
            get {
                return ResourceManager.GetString("Ticket_Severity_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site not found..
        /// </summary>
        public static string Ticket_Site_NotFound {
            get {
                return ResourceManager.GetString("Ticket_Site_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiteId is required..
        /// </summary>
        public static string Ticket_SiteId_Required {
            get {
                return ResourceManager.GetString("Ticket_SiteId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket severity is invalid..
        /// </summary>
        public static string Ticket_Status_Invalid {
            get {
                return ResourceManager.GetString("Ticket_Status_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is required..
        /// </summary>
        public static string Ticket_Subject_Required {
            get {
                return ResourceManager.GetString("Ticket_Subject_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Password not valid TryAgain!.
        /// </summary>
        public static string WrongLoginCredintial {
            get {
                return ResourceManager.GetString("WrongLoginCredintial", resourceCulture);
            }
        }
    }
}
